server:
  port: 8888

eureka:
  instance:
    hostname: config
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:user@localhost:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Goode-Man/graduation-project
          search-paths: config-repo
          spring.cloud.config.label: master
          spring.cloud.config.server.git.username: 526156395@qq.com
          spring.cloud.config.server.git.password: lfy526156395
    #        native:
    #          search-locations: file:/config-repo
    #        bootstrap: true
    bus:
      enabled: true
      trace:
        enabled: true
  application:
    name: config
  rabbitmq:
    host: rabbitmq

  security:
    user:
      name: user
      password: user

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
