server:
  port: 8024
spring:
  application:
    name: mail
  mail:
    host: smtp.qq.com
    username: 2796892886@qq.com
    password: 密码
    port: 465
    properties:
      mail.debug: false
      mail.smtp.auth: true
      mail.smtp.port: 587
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.socketFactory: sf
  freemarker:
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true


lance:
  mail:
    sender: 2796892886@qq.com

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:user@localhost:8761/eureka/