server:
  port: 8022
spring:
  application:
    name: file
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      fail-fast: true
      username: user
      password: user
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
#  security:
#    user:
#      name: user
#      password: user
  datasource:
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=GMT
    username: root
    password: 5261
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:user@localhost:8761/eureka/
